---
title: "Welcome!"
---

# ON LiMiT Data Management Plan (DMP)

ON LiMiT is a research project aimed at investigating how weight loss
through meal replacement, followed by a diet that is either low- or
high-carbohydrate, with or without exercise, affects the maintenance of
remission in people with type 2 diabetes. Type 2 diabetes is a major
public health issue both in Denmark and globally, as the disease
increases the risk of serious complications such as cardiovascular
disease, eye disorders, and neurological damage. It reduces quality of
life and imposes a significant economic burden on society. Achieving
remission---and particularly maintaining remission through diet and
physical activity---could improve population health, including for those
with type 2 diabetes, and benefit the economy.

## Collaborations

The project is being conducted in Aarhus, Odense, and Copenhagen and is
a collaboration between Steno Diabetes Center Aarhus, Steno Diabetes
Center Odense, Steno Diabetes Center Copenhagen, Bispebjerg Hospital,
and the Department of Nutrition, Exercise and Sports and the Center for
Basic Metabolic Research at the University of Copenhagen.

## Purpose of the data management plan

Although the ON LiMiT study has been classified as not being a clinical
drug trial by the Danish Medical Agency (DMA), we have chosen to align
with best practices for clinical trials wherever possible. While a Data
Management Plan (DMP) is not mandatory for a study such as ON LiMiT, it
is strongly recommended for all research studies. This DMP ensures
transparency, compliance, and integrity in handling participant data
throughout the project lifecycle.

## Governance and maintenance

We follow a modified version of a DMP template from
[DeiC](https://deic.dk/en/data-management), mainly around how we
describe access to data.

This document will be maintained by members of the study team and has
been approved for publication on the project website by the Project
Manager on behalf of the Chief Investigator.
