# Data sources and flow

ON LiMiT collects data from multiple sources, including biological samples,
questionnaires, and electronic tools. Data originates from participants,
healthcare professionals, and bioanalysts, and is stored securely on GenomeDK
servers for subsequent analysis. Excluding the participants who contribute their
data to the study, there are two key user groups: data producers and data
consumers.

There are four main users within the data producer group:

- Bioanalysts who process, measure, and analyze the physical biological samples
  such as blood.
- Healthcare professionals who work with the participants in the study, filling
  in forms and taking physical measurements such as height.
- Data (or software) engineers who build and develop the digital infrastructure
  and processes to take the raw data and clean it into analysis-ready data.
- Data managers (and distributors) who help maintain the stored data and
  coordinate with data consumers in retrieving and distributing specific data to
  do analyses.

For data consumers, there is really only one user type: the researcher. This is
someone who is interested in doing analysis of existing data.

The below @fig-c4-context illustrates the context of ON LiMiT, key users, and
data providers:

```{mermaid}
%%| label: fig-c4-context
%%| fig-cap: >-
%%|   Diagram showing a basic overview of ON LiMiT, its anticipated users, and
%%|   data providers.
%%| fig-alt: >-
%%|   Flowchart diagram with arrows coming from producers and consumers towards
%%|   the three systems, data collectors, ON LiMiT, and Denmark Statistics.
%%| fig-width: 100%

flowchart TD
  Producers
  Consumers

  onlimit[["ON LiMiT<br>[system]<br>Made up of REDCap, which receives raw data and GenomeDK, which stores cleaned data."]]
  dst[["Denmark Statistics<br>[system]<br>Closed server where data from ON LiMiT can be uploaded."]]
  collectors[["Data Collectors<br>[systems]<br>LIVA, MyFood24, Food preferences app, SENS, Libre CGM, biological clinical samples."]]

  Producers --> collectors --> onlimit
  Consumers --> onlimit & dst
  onlimit --> dst
```

## Technical infrastructure

The @fig-c4-container diagram shows the main components of the ON LiMiT data
infrastructure, including data sources, storage, and analysis tools. It provides
an overview of how the data is collected, stored, and made available for
analysis.

```{mermaid}
%%| label: fig-c4-container
%%| fig-cap: >-
%%|   Diagram showing the main components of ON LiMiT data infrastructure,
%%|   including data sources, storage, and analysis tools.
%%| fig-width: 100%

flowchart TD
  Data[("Data<br>[software systems]<br>All electronic data generated from various tools" )]
  Samples(["Biological samples<br>[objects]<br>Collected from study participants and stored on ice during transport"])
  Redcap[("REDCap<br>[database]<br>Used by staff to collect data about participants")]
  Biobank[["Biobank<br>[facility]<br>Storage-facility for biological samples"]]
  Sprout[["Seedcase Data Package<br>[software]<br>Tools to build the data as a package for easier consumption"]]
  Genome[("GenomeDK<br>[system]<br>HPC facility where processed data will be stored")]
  Analysis[["Analysis Area on GenomeDK<br>[system]<br>Facility via GenomeDK where data can be made available for researchers"]]
  DS[["Denmark Statistics<br>[system]<br>Closed analysis tool where data from ON LiMiT can be uploaded"]]
  Flower[["Seedcase Flower<br>[software]<br>Tool to create a website showing metadata of ON LiMiT data"]]
  Website[("Website<br>[systems]<br>Website of the data dictionary for ON LiMiT data")]
  Researcher(["Researcher<br>[person]<br>Interested in doing additional analysis of existing data"])

  subgraph i1 [ON LiMiT environment]
      Redcap --> Sprout
      Biobank ~~~ Sprout
      subgraph i2 [ ]
          Sprout --> Genome
          Genome --> Flower
          Genome -.-> Analysis
      end
      Genome --> DS
      Flower --> Website
  end

  Data:::external --> Sprout
  Data --> Redcap
  i1:::system
  i2:::hidden
  Samples:::external --> Redcap
  Samples --> Biobank
  Researcher:::external
  Researcher --> DS
  Researcher --> Analysis
  Researcher --> Website

  classDef system fill:none
  classDef external fill:lightgrey
  classDef hidden fill:none, stroke-width:0
```

### Devices, scanners, and other equipment

The main study will be conducted at five different sites, and data will be
collected using a variety of devices. A few will be unique to one or two sites,
but most will be used at all sites.

The following equipment will be used for data collection:

- [ECG](https://en.wikipedia.org/wiki/Electrocardiography) (all sites) for
  measuring heart rate and rhythm. This will be done for all participants.
- [DXA](https://en.wikipedia.org/wiki/Dual-energy_X-ray_absorptiometry)scanner
  (all sites) for measuring body composition and bone density. This will be done
  for participants in the intervention arms.
- [Fibroscanner](https://en.wikipedia.org/wiki/Elastography#Transient_elastography)
  (four sites) for measuring liver stiffness. This will be done for participants
  in the intervention arms.
- [iMotion Food
  preference](https://imotions.com/customer-stories/food-reward-biometrics/)
  (two sites) for establishing food preferences. This will be done for
  participants in the intervention arms.
- [VO2Max](https://en.wikipedia.org/wiki/VO2_max), bike (all sites) for
  measuring maximal oxygen uptake during cycling. This will be done for
  participants in the intervention arms.
- [VO2Max](https://en.wikipedia.org/wiki/VO2_max), breathing (all sites) for
  measuring maximal oxygen uptake during cycling. This will be done for
  participants in the intervention arms.
- [CGM](https://en.wikipedia.org/wiki/Continuous_glucose_monitoring) (all sites)
  for measuring glucose levels. This will be done for all participants.
- [SENS motion](https://en.wikipedia.org/wiki/Physical_activity) (all sites) for
  measuring physical activity. This will be done for participants in the
  intervention arms.

For a detailed overview of the equipment used at each site, including scanner
type, site, make, and model, please refer to the [Equipment
overview](/supplemental/equipment.qmd) section.

### Tests specific to one or more sites

Most of the tests mentioned above will be done at all sites, but a few will be
specific to one or two sites. The following tests will be conducted at specific
sites:

- Fibroscanner: This test will be conducted at Steno Aarhus, Steno Copenhagen,
  Steno Odense, and Bispebjerg Hospital for measuring liver stiffness in
  participants in the intervention arms.
- iMotion Food preference: This test will be conducted at Steno Copenhagen and
  NEXS (Department of Nutrition, Exercise and Sports, University of Copenhagen)
  for establishing food preferences in participants in the intervention arms.
- Finapres: This test will be conducted at Bispebjerg Hospital for measuring
  cholesterol levels in participants in the intervention arms.
- [Mixed Meal Tolerance
  Test](https://prosciento.com/wp-content/uploads/2022/01/ProSciento-Fact-Sheet-OGT-and-MMT.pdf):
  This test will be conducted at Steno Aarhus, Steno Odense, and Bispebjerg
  Hospital for measuring glucose levels in participants in the intervention
  arms.
- [Oral Glucose Tolerance
  Test](https://prosciento.com/wp-content/uploads/2022/01/ProSciento-Fact-Sheet-OGT-and-MMT.pdf):
  This test will be conducted at NEXS (Department of Nutrition, Exercise and
  Sports, University of Copenhagen) for measuring glucose levels in participants
  in the intervention arms.
