---
date: 2026-09-14
date-modified: 2026-09-14
---

# Equipment overview

Below is a table of the equipment used at each site. The table includes the
scanner type, site, make, and model of each piece of equipment. See below for
site abbreviations.

  | Scanner type       | Site                                   | Make                                         | Model                        |
  | ------------------ | -------------------------------------- | -------------------------------------------- | ---------------------------- |
  | CGM                | All Sites                              | Abbott                                       | Freestyle LibreProiQ         |
  | DXA                | Bispebjerg Hospital                    | GE Healthcare                                | Lunar iDXA Waukesha, WI, USA |
  | DXA                | NEXS                                   | GE Healthcare                                | Lunar Prodigy iDXA           |
  | DXA                | Steno, Aarhus                          | Tromp                                        | Hologic Horizon-A            |
  | DXA                | Steno, Copenhagen                      | GE Medical Systems (Wisconsin, USA)          | Lunar iDXA                   |
  | DXA                | Steno, Odense                          |                                              |                              |
  | EKG                | Bispebjerg Hospital                    |                                              |                              |
  | EKG                | NEXS                                   | Intramedic A/S                               | Vyntus CPX added module      |
  | EKG                | Steno, Aarhus                          |                                              |                              |
  | EKG                | Steno, Copenhagen                      | GE Healthcare                                | MAC VU360 Resting EKG        |
  | EKG                | Steno, Odense                          |                                              |                              |
  | Fibro              | Bispebjerg Hospital                    | To be procured                               |                              |
  | Fibro              | Steno, Aarhus                          | To be procured                               |                              |
  | Fibro              | Steno, Copenhagen                      | Echosens (Paris, France)                     | Fibroscan Compact 530        |
  | Finapres           | Bispebjerg Hospital; Steno, Copenhagen | Finapres                                     | NOVA                         |
  | FoodPreference     | NEXS                                   |                                              |                              |
  | FoodPreference     | Steno, Copenhagen                      | Tobii (Stockholm, Sweden)                    | X2-60 device                 |
  | SENS               | All Sites                              | Sens motion                                  | SENS motion PLUS             |
  | VO2Max (bike)      | Bispebjerg Hospital                    |                                              |                              |
  | VO2Max (bike)      | NEXS                                   | Jaeger electronically braked cycle ergometer | ER800                        |
  | VO2Max (bike)      | Steno, Aarhus                          | SRM                                          |                              |
  | VO2Max (bike)      | Steno, Copenhagen                      | Lode (Groningen, The Netherlands)            | Corival cpet                 |
  | VO2Max (bike)      | Steno, Odense                          |                                              |                              |
  | VO2Max (breathing) | Bispebjerg Hospital                    |                                              |                              |
  | VO2Max (breathing) | NEXS                                   | Intramedic A/S                               | Vyntus CPX                   |
  | VO2Max (breathing) | Steno, Aarhus                          | COSMED                                       | Quark CPET                   |
  | VO2Max (breathing) | Steno, Copenhagen                      | Jaeger (previously Vyaire)                   | Vyntus CPX                   |
  | VO2Max (breathing) | Steno, Odense                          |                                              |                              |

  : List of all scanners used to collect data, their make and model, and which
    site they are used at.
